# fly.toml app configuration file generated for bundiscordbot on 2023-09-14T22:20:46-07:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "bundiscordbot"
primary_region = "sjc"

[build]

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = false
  auto_start_machines = true
  min_machines_running = 1
  processes = ["app"]
